CREATE ROLE DATA_SECURITY_ROLE;

GRANT SELECT, UPDATE, INSERT ON secure_data TO DATA_SECURITY_ROLE;
GRANT EXECUTE ON retrieve_decrypted_data TO DATA_SECURITY_ROLE;
GRANT SELECT ON secure_data_view TO DATA_SECURITY_ROLE;

GRANT DATA_SECURITY_ROLE TO admin_user;